name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: python:3.14-slim

    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

    services:
      db:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
        version: "0.11.23"

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Run lint check
      run: uv run ruff check .

    - name: Run format check
      run: uv run ruff format --check .

    - name: Run cognitive complexity check
      run: uv run complexipy .

    - name: Run tests
      run: uv run pytest
